version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - node
    ports:
       - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  node:
    image: node:14
    #command: npm run fake
    networks:
      - app
    ports:
      - '3010'
      - '3050'
      - '4443'
    volumes:
      - .:/app:delegated
    working_dir: /app

  redis:
    image: redis:3
    networks:
      - app
    ports:
      - '6379'
